---
services:
  squid:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: squid_proxy
    ports:
      - "3128:3128"
      - "443:443"
    volumes:
      - ./config/squid.conf:/etc/squid/squid.conf:ro
      - ./config/passwd:/etc/squid/passwd:ro
    environment:
      - TZ=UTC
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
        - proxy_network

networks:
  proxy_network:
    driver: bridge